import type { Metadata } from 'next'
import { Inter, DotGothic16 } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })
const dotGothic16 = DotGothic16({
  subsets: ['cyrillic'],
  weight: '400'
})
export const metadata: Metadata = {
  title: 'F2E Tool Box',
  description: 'Generated by Create Next App ',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="container m-auto">
      <div className={dotGothic16.className}>{children}</div>
    </div>
  )
}
